### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Pappet** [Larwck/Graphical_Overmap#1]
I get this Error if i try to start a game. 
```
DEBUG    : Error: data/mods//Graphical_Overmap/fonts.json: line 1:1: member not found: type

{
^

  "typeface": "unifont",
  "map_typeface": "unifont",


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 737
```
I instaled the mod, changed the font size, restarted and added the mod to the world. What is missing?

**Comment by MrOysterhead44** [comment]
I was able to fix this by deleting fonts.json in data/mods/graphical_overmap.

**Comment by Larwck** [comment]
Yeah if you're installing from here on build #9942 or later you will need to delete fonts.json as MrOysterhead44 says. Once "Graphical Overmap update #35792" is merged to CleverRaven this shouldn't be an issue anymore.
